name: fixit_monitor
description: Simple web monitoring & approval (no backend)
publish_to: "none" # this prevents publishing to pub.dev

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.0  # moved outside 'flutter:'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
